### ISSUE TITLE
Missing ImportStreamSource class when using importDump.php

### ISSUE THREAD

**Issue by pilhokim** [mediawiki4intranet/core#2]
Firstly thanks a lot for the great contribution!

I tested mediawiki4intranet and am stuck in the data moving process.

While moving data from my old wiki to mediawiki4intranet, I tried to use importDump.php for several hundreds MB xml file. It complains "Missing ImportStreamSource class"  as shown below:

```
root@3f4a8b7dfd55:/var/www/html/wiki/maintenance# php importDump.php --conf ../LocalSettings.php /root/temp/wiki_export.xml.gz
** WARNING: IntraACL security checks are disabled because
** $_SERVER[SERVER_NAME] is empty, which probably means we are in console
PHP Fatal error:  Class 'ImportStreamSource' not found in /var/www/html/wiki/maintenance/importDump.php on line 260
```

Could you plz advise what to do? Or else should I wait til you release mediawiki4intranet for Mediawiki 1.26?

Thank you a lot in advance!

**Comment by vitalif** [comment]
1) importDump and dumpBackup were basically broken until the last week and it seems you're using an older version; note that you should always do `git pull --rebase` instead of just `git pull` to update mediawiki4intranet-core because a patch series is often rebased instead of adding new commits
2) our import/export is reworked so much that it does not support *.gz and *.bz2, so ungzip your file before importing
3) if you have images dumped inside your xml file (original mediawiki format which appeared much later than our "multipart" zip with xml and binary files inside) - I think the support for importing such files is also broken (this is easy to fix of course, maybe I'll even do it now). MediaWiki4Intranet now supports only 2 options for importing/exporting uploads - (1) by HTTP download from source wiki (destination wiki will download the files by itself while importing by their 'src' urls) (2) from export ZIP archive generated by another mediawiki4intranet. Original Mediawiki format with base64 has 30% size overhead... but of course it should also be supported...
4) you can upgrade to mediawiki4intranet just by overwriting the code of original 1.26 wiki with mediawiki4intranet 1.26 core. the only thing which should be ran after it is configs/maintenance/file-upload-renamer.php (this will rename old versions of files to have _their_own_ timestamp in name instead of an approximate timestamp of the next revision like it's in the original). and of course make a backup first.

**Comment by vitalif** [comment]
P.S: mediawiki4intranet for Mediawiki 1.26 is already released, here on github it's the default branch :)

**Comment by vitalif** [comment]
OK I've just fixed import/export support for XML-Base64 files.

**Comment by pilhokim** [comment]
Thank you Vitaliy for VERY fast responses :100:  It is impressive. Let me follow your advice on the coming week and reply back with details to close this issue. Will get back soon.

**Comment by vitalif** [comment]
:) you're welcome

**Comment by pilhokim** [comment]
It works now! Here is the step to complete the data importing process.

- As advised, I used the latest code here in GitHub and followed the instruction to setup Mediawiki4Intranet.
- Data exporting & importing between different wiki versions was very troublesome. As the latest wiki version of Mediawiki4Intranet is 1.26, I also upgraded my existing wiki engine to 1.26. After making both to 1.26, I simply exported the entire DB with stored procedures and create a new DB for Mediawiki4Intranet to copy into it.
- An old image directory was also directly copied to the new wiki.
- All wiki pages and images are safely moved now! 
- I made a number of minor modifications for internationalization.
- I am working on a number of conflicts with extensions and skins that we have been using. I will post separated issues :)
- I have linked Mediawiki4Intranet to our company's Microsoft Active Directory login service. The login works like a charm with the full control on the page access with your great intra4ACL definitions.
- I have setup this new Mediawiki4Intranet within the Docker environment built atop synctree/mediawiki image. I see no difference between the existing wiki on the full Linux server and this new wiki on Docker. 

Thank you again, Vitalif!
